### ISSUE TITLE
(Minor) Recent update to Karen broke "Press Enter to Exit" in the installer

### ISSUE THREAD

**Issue by Asinin3** [Difegue/Karen#3]
![powershell_GDXvaJS0pK](https://user-images.githubusercontent.com/15137035/58932624-9b834080-87a3-11e9-9d01-d6806e0912d4.png)
I guess it was this commit? https://github.com/Difegue/Karen/commit/61fe13573c4d3623197608b7dbb6d215a17d13f3

**Comment by Difegue** [comment]
Yeah, I added NoExit after seeing some installer errors closing the window immediately. It's better to have a window you can close manually than the opposite. I'll try making the "Press Enter" prompt actively shut down the powershell host for a next release.

**Comment by Difegue** [comment]
Fixed™ by means of brutally changing the entire installer.
