### ISSUE TITLE
[Suggestion] Add debug mode option to Karen

### ISSUE THREAD

**Issue by Asinin3** [Difegue/Karen#7]
I've had a lot of trouble trying to enable debug mode when LRR has been in a loop of crashing/running into mojolicious errors shortly after starting. Even if i managed to reach the settings page and enable debug mode and hit save it would still be turned off when I restarted when I clicked stop > start or quit karen entirely and re-opened. 

As such I think it would be a really good idea to allow people to enable the debug mode in Karen so you don't have to start LRR, enable it and then restart again.

**Comment by Difegue** [comment]
Done in 2130f2a58b993efcd288d3568db4b56de1338d47 .
